# Generated by Django 3.1 on 2023-05-18 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=255)),
                ('jenis', models.CharField(choices=[('AKTIVA', 'Aktiva'), ('BIAYA', 'Biaya'), ('HPP', 'Harga Pokok Penjualan'), ('PENDAPATAN', 'Pendapatan'), ('PASIVA', 'Pasiva')], max_length=10)),
                ('is_akun_kas', models.BooleanField(default=False)),
                ('account_induk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keuangan.account')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
