# Generated by Django 3.1 on 2023-05-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='kode',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
