# Generated by Django 3.1 on 2023-05-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0002_auto_20230518_1411'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='COA',
        ),
        migrations.AlterModelOptions(
            name='coa',
            options={'verbose_name': 'COA', 'verbose_name_plural': 'COAs'},
        ),
    ]
