# Generated by Django 3.1 on 2023-05-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0004_auto_20230518_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='ap',
            name='tgl_transaksi',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ap',
            name='tgl_jatuh_tempo',
            field=models.DateTimeField(),
        ),
    ]
