# Generated by Django 3.1 on 2023-05-19 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kesantrian', '0002_auto_20230518_1346'),
        ('keuangan', '0005_auto_20230518_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ap',
            name='user_create',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ap',
            name='user_modify',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coa',
            name='user_create',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coa',
            name='user_modify',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaksi', models.IntegerField()),
                ('kelas_model', models.CharField(max_length=255)),
                ('no_bukti_transaksi', models.CharField(max_length=255)),
                ('tgl_transaksi', models.DateTimeField(null=True)),
                ('nominal', models.IntegerField()),
                ('tgl_jatuh_tempo', models.DateTimeField()),
                ('terbayar', models.IntegerField()),
                ('sisa', models.IntegerField()),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modify', models.DateTimeField(auto_now=True, null=True)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesantrian.stakeholder')),
                ('user_create', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_created', to=settings.AUTH_USER_MODEL)),
                ('user_modify', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AR',
                'verbose_name_plural': 'ARs',
            },
        ),
    ]
