# Generated by Django 3.1 on 2022-11-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='variations',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='variations',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
