# Generated by Django 3.1 on 2023-05-18 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('nama', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kelas',
                'verbose_name_plural': 'Kelas-kelas',
            },
        ),
        migrations.CreateModel(
            name='StakeHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('Santri', 'Santri'), ('Pengajar', 'Pengajar'), ('Pengurus', 'Pengurus'), ('Supplier', 'Supplier'), ('Lainnya', 'Lainnya')], max_length=20)),
                ('kode', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'StakeHolder',
                'verbose_name_plural': 'StakeHolders',
            },
        ),
        migrations.CreateModel(
            name='Ustadz',
            fields=[
                ('stakeholder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kesantrian.stakeholder')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('mulai_bergabung', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ustadz',
                'verbose_name_plural': 'Ustadz-Ustadz',
            },
            bases=('kesantrian.stakeholder',),
        ),
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('stakeholder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kesantrian.stakeholder')),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('orang_tua', models.CharField(max_length=100)),
                ('spp', models.IntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kesantrian.kelas')),
            ],
            options={
                'verbose_name': 'Santri',
                'verbose_name_plural': 'Santris',
            },
            bases=('kesantrian.stakeholder',),
        ),
        migrations.AddField(
            model_name='kelas',
            name='wali_kelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kesantrian.ustadz'),
        ),
    ]
